README.md, start.sh
- Bash script to automate Development workflow (tested on Ubuntu 20.04.4 LTS)
- Updated readme to clarify ngrok authentication
=> Start script & updated readme

components/CartTesting.tsx, components/ProductPage.tsx, context/CartContext.js, lib/hooks/useCheckoutOnStore.ts, lib/hooks/useProductOnStore.ts, pages/api/checkout/index.ts, pages/api/product/index.ts, pages/campaign/[handle]/index.tsx, pages/campaign/[handle]/products/[product_id]/index.tsx
=> Merging feat/cart state

components/CampaignForm.tsx, components/Navbar.tsx, components/cart/CartItem.tsx, components/cart/CartItems.tsx, components/cart/SlidingCart.tsx, components/general/icons/CartEmpty.tsx, components/general/icons/CartFilled.tsx, context/CartContext.tsx
1. Cart count will appear on the navbar when there are items in the cart
2. Made the cart responsive
3. Cart will show empty cart message when there are no items in the cart
4. Updated styling code
=> Updated Cart Styling and Cart Count in the navbar icon

pages/app/index.tsx, pages/app/settings/index.tsx
- Adds a preview button
- Only shows config box when there is no subdomain added
- After subdomain added for first time redirects to campaign page 
- Check preview button works in local & prod
- Check it only shows the add campaign section after a subdomain is added
- Check redirect works only on first time setup of settings
=> Feat/Preview Button & Subdomain settings

context/BillingProvider.tsx, lib/types.ts, package.json, pages/_app.tsx, pages/api/apps/billing/cancel/index.ts, pages/api/apps/billing/index.ts, pages/app/onboarding/index.tsx, pages/app/settings/index.tsx, yarn.lock
Implements subscription purchase screen and management on settings page
When you open the app it should prompt you to choose a subscription plan. Once you complete the purchase of a plan you should have access to the rest of the app. 
On the settings page you should see the plan you're subscribed to and be able to cancel the subscription.
After canceling your subscription you should be redirected to the plan selection screen.
=> feat: Implement subscription flow

components/CampaignForm.tsx, components/Page.tsx, components/PrimaryButton.tsx, components/SecondaryButton.tsx, lib/helper/objects.ts, lib/hooks/app/useStoreThemeForm.ts, pages/api/products/index.ts, pages/app/campaign/[id].tsx, pages/app/campaign/new.tsx, pages/app/index.tsx, pages/app/settings/index.tsx, pages/app/test.jsx, pages/campaign/[handle]/collections/[collection_id]/index.tsx, pages/campaign/[handle]/index.tsx, pages/campaign/[handle]/products/[product_id]/index.tsx
Various small misc fixes:
- Adds spacing to bottom of forms
- Adds "store is in draft mode" bar to draft stores
- Buttons now have default color and are no longer transparent
- Collection/Product comparison fixed to use a deepEquality comparison rather than just comparing length
- Preview button now on campaign form too
- Campaign form opens to top of form instead of halfway scrolled down
- Check draft mode bar appears only on draft stores
- Check when collections/products are changed that the save button only appears when the selection is different to the previously saved values
- Check there are no scroll issues with the campaign form
=> Feat/App Pages Fixes

pages/api/campaign/index.ts
extract subdomain inside campaign endpoint dynamically
=> chore: extract subdomain inside campaign endpoint dynamically

pages/app/index.tsx
Add preview token query to the preview button in the index page
=> chore: add query params to preview url

components/CampaignForm.tsx, lib/hooks/app/useCampaignForm.ts, pages/app/index.tsx
Use Yup for handle name validation, and disable "Save" button depending on formState
=> fix: use Yup for handle name validation

lib/campaign/getCampaignForRequest.ts
_Description of the pull request, what changed_
=> debug: Add logs

components/campaign/Page.tsx, lib/types.ts, utils/flattenCampaignFields.ts
_Description of the pull request, what changed_
=> feat: Add preview button to campaign page

lib/hooks/app/useCampaignForm.ts
_Description of the pull request, what changed_
=> fix: Refresh server side props after campaign update

components/campaign/CartCustomizationFormSlice.tsx
Added color picker for cart background color
=> chore: add color picker for cart bg

components/campaign/AccessControlFormSlice.tsx, pages/app/settings/index.tsx
- A few copy changes on **Overview** tab
- **Logo** image selector remove button appears if image is present
Logo image selector
Copy changes
=> Minor copy edits on admin

components/CampaignHeader.tsx, lib/theme/getThemeConfig.ts, pages/[campaign_handle]/index.tsx
Display Campaign Title and Description on campaign landing page
=> feat: show campaign title and description

components/LogoTitle.tsx, pages/[campaign_handle]/password.tsx
Fix the nav logo not getting updated
=> fix: switch to img tag to avoid stale images getting displayed

components/ProductPage.tsx, components/atelier-landing-page/Navbar/NavDrawer.tsx, components/cart/MiniCart.tsx, components/navigation/MobileNav.tsx, lib/hooks/app/useStoreThemeForm.ts, pages/app/settings/index.tsx
- Put spacing between two columns in PDP
- Changed some `class` attributes to `className`
PDP
=> Product page spacing

pages/[campaign_handle]/password.tsx
Make image fill the available space
=> fix: Fix image size

components/Header.tsx, components/campaign/Page.tsx, pages/app/settings/index.tsx
- Hiding logo position setting when no logo is present
- Make navigation bar & page background the same color
- Remove collection card on campaign page
- Border radius helptext update
Position setting when logo present
Position setting when logo not present
Background color label update
Remove collection image on campaign page
Border radius helptext update
=> Multiple QA tickets

components/LogoTitle.tsx, lib/hooks/app/useStoreMetadataForm.ts, lib/theme/getThemeConfig.ts, pages/[campaign_handle]/password.tsx, pages/app/settings/index.tsx
An extension to [PR #71](https://github.com/lumberdev/atelier/pull/71)
Work done for favicon
=> Image update on favicon element

components/PreviewModeBanner.tsx, pages/app/settings/index.tsx
- Domain name validation on settings tab
initial state
error state
valid state
=> Domain name validation

pages/api/apps/settings/index.ts, pages/app/settings/index.tsx
extension to previous work for domain name validator
=> Domain name validator - no cap, not hostname

pages/app/onboarding/index.tsx
=> Beta copy change

components/atelier-landing-page/Footer/index.tsx
_Description of the pull request, what changed_
=> chore: use faq in footer

utils/webhooks/app_uninstalled.js
- Make sure the app goes through OAuth procedure when installing/reinstalling
How to uninstall:
How to reinstall:
=> OAuth flow fix - deletes data when app removed
